"""
Your task in this exercise has two steps:

- audit the OSMFILE and change the variable 'mapping' to reflect the changes needed to fix 
    the unexpected street types to the appropriate ones in the expected list.
    You have to add mappings only for the actual problems you find in this OSMFILE,
    not a generalized solution, since that may and will depend on the particular area you are auditing.
- write the update_name function, to actually fix the street name.
    The function takes a string with street name as an argument and should return the fixed name
    We have provided a simple test so that you see what exactly is expected
"""
import xml.etree.cElementTree as ET
from collections import defaultdict
import re
import pprint

OSMFILE = "miami_florida.osm"
street_type_re = re.compile(r'\b\S+\.?$', re.IGNORECASE)

expected = ["Street", "Avenue", "Boulevard", "Drive", "Court", "Place", "Square", "Lane", "Road", "Trail", "Parkway",
            "Commons", "Lane", "Manor", "Highway", "North", "NorthWest", "Parkway", "Point", "Terrace"]

mapping = {
    "Ave": "Avenue",
    "Ave.": "Avenue",
    "AVE": "Avenue",
    "Blvd": "Boulevard",
    "BLVD": "Boulevard",
    #"Cir": "Circle",
    "Ct": "Court",
    "Dr": "Drive",
    "HWY": "Highway",
    "Hwy": "Highway",
    "Ln": "Lane",
    "Mnr": "Manor",
    "N.": "North",
    "NW": "NorthWest",
    "Pkwy": "Parkway",
    "Pt": "Point",
    "Rd.": "Road",
    "Rd": "Road",
    "St": "Street",
    "St.": "Street",
    "ST": "Street",
    "Ter": "Terrace",
    "Trce": "Terrace"
}


def audit_street_type(street_types, street_name):
    m = street_type_re.search(street_name)
    if m:
        street_type = m.group()
        if street_type not in expected:
            street_types[street_type].add(street_name)


def is_street_name(elem):
    return elem.attrib['k'] == "addr:street"


def audit(osmfile):
    osm_file = open(osmfile, "r")
    street_types = defaultdict(set)
    for event, elem in ET.iterparse(osm_file, events=("start",)):

        if elem.tag == "node" or elem.tag == "way":
            for tag in elem.iter("tag"):
                if is_street_name(tag):
                    audit_street_type(street_types, tag.attrib['v'])

    return street_types


def update_name(name, mapping):
    for key in mapping.keys():
        if key in name:
            return name.replace(key, mapping[key])

    return name


def test():
    st_types = audit(OSMFILE)
    #print len(st_types)
    #pprint.pprint(dict(st_types))

    assert len(st_types) == 94

    for st_type, ways in st_types.iteritems():
        for name in ways:
            better_name = update_name(name, mapping)
            print name, "=>", better_name
            if name == "North Biscayne Blvd":
                assert better_name == "North Biscayne Boulevard"
            if name == "Golf Club Rd":
                assert better_name == "Golf Club Road"


if __name__ == '__main__':
    test()

'''
    {'1': set(['US Highway 1']),
 '104': set(['Linton Blvd Suite 104']),
 '108': set(['NW 20th Street, #108']),
 '15-103': set(['West Palmetto Park Road Suite 15-103']),
 '177': set(['South Dixie Highway #177']),
 '19': set(['Harding Ave #19']),
 '207': set(['324 Datura St #207', 'South Dixie Highway, Suite 207']),
 '209': set(['Sheridan Street, Ste 209']),
 '2111': set(['Southwest 190th Street, #2111']),
 '27': set(['Hwy 27']),
 '322': set(['E. Commercial Blvd. Ste. 322']),
 '328': set(['Biscayne Boulevard, Suite 328']),
 '5979': set(['5979']),
 '7': set(['State Road 7']),
 '8,9,10': set(['W 49 St Suite 8,9,10']),
 '826': set(['826']),
 '84': set(['11860 W State Road 84',
            '11880 W State Road 84',
            'West State Road 84']),
 '918': set(['Biscayne Blvd Ste 918']),
 'AVE': set(['28450 SW 152ND AVE']),
 'Atlanta': set(['Atlanta']),
 'Augusta': set(['Augusta']),
 'Ave': set(['4000 SW 64th Ave',
             '74th Ave',
             'Bedford Ave',
             'Collins Ave',
             'Cordova Ave',
             'Corporate Ave',
             'E Gardenia Ave',
             'E Seneca Ave',
             'E Whitewater Ave',
             'Enterprise Ave',
             'Granada Ave',
             'Harding Ave',
             'Isles Of Weston Ave',
             'Islewood Ave',
             'Lakeview Ave',
             'Lenox Ave',
             'Meridian Ave',
             'N Gardenia Ave',
             'N. Meridian Ave',
             'NE 2nd Ave',
             'NE 5th Ave',
             'NW 41 Ave',
             'NW 66th Ave',
             'NW 67th Ave',
             'NW 73rd Ave',
             'Park Ave',
             'Rainbow Ave',
             'S Gardenia Ave',
             'S Whitewater Ave',
             'SE 1st Ave',
             'SW 148th Ave',
             'SW 167th Ave',
             'SW 168th Ave',
             'SW 169th Ave',
             'SW 170th Ave',
             'SW 17th Ave',
             'SW 202nd Ave',
             'SW 62nd Ave',
             'SW 63rd Ave',
             'SW 68th Ave',
             'SW 72nd Ave',
             'SW 87th Ave',
             'Seneca Ave',
             'W Gardenia Ave',
             'W Whitewater Ave',
             'Washington Ave',
             'West Ave',
             'Westgate Ave']),
 'Ave.': set(['Jefferson Ave.']),
 'BLVD': set(['East Las Olas BLVD']),
 'Birkdale': set(['Birkdale']),
 'Blvd': set(['Biscayne Blvd',
              'Blatt Blvd',
              'Bonaventure Blvd',
              'Cleveland Clinc Blvd',
              'Corporate Lakes Blvd',
              'Crandon Blvd',
              'Dade Blvd',
              'E Atlantic Blvd',
              'E. Commercial Blvd',
              'FAU Blvd',
              'Fairlake Blvd',
              'Falls Blvd',
              'Forest Hills Blvd',
              'Gables Blvd',
              'Indian Trace Blvd',
              'Lake Blvd',
              'Landings Blvd',
              'Meadows Blvd',
              'N Biscayne Blvd',
              'N Corporate Lakes Blvd',
              'North Biscayne Blvd',
              'North Lake Blvd',
              'Okeechobee Blvd',
              'Orange Blvd',
              'Palm Blvd',
              'Pines Blvd',
              'Promenade Blvd',
              'Royal Palm Blvd',
              'S Corporate Lakes Blvd',
              'S Ocean Blvd',
              'Saint Andrews Blvd',
              'Seabreeze Blvd',
              'Town Center Blvd',
              'Universal Blvd',
              'Vista Park Blvd',
              'W Commercial Blvd',
              'W Corporate Lakes Blvd',
              'W Hillsboro Blvd']),
 'Blvd.': set(['Avocado Blvd.',
               'Champion Blvd.',
               'East Las Olas Blvd.',
               'Pines Blvd.',
               'Seabreeze Blvd.',
               'Seminole Blvd.']),
 'Bnd': set(['Alexander Bnd',
             'Cordoba Bnd',
             'Eagle Bnd',
             'Orchid Bnd',
             'Osprey Bnd',
             'Sapphire Bnd',
             'Tradewinds Bnd']),
 'Capistrano': set(['Capistrano']),
 'Causeway': set(['Rickenbacker Causeway']),
 'Charleston': set(['Charleston']),
 'Cir': set(['Alexandra Cir',
             'Bayview Cir',
             'Beechwood Cir',
             'Blue Jay Cir',
             'Camella Cir',
             'Camellia Cir',
             'Chenille Cir',
             'Coconut Cir',
             'Cottonwood Cir',
             'Crestview Cir',
             'Crestwood Cir',
             'Dockside Cir',
             'Dogwood Cir',
             'E Melrose Cir',
             'Eagle Run Cir',
             'Estancia Cir',
             'Fairway Cir',
             'Falcon Ridge Cir',
             'Garnet Cir',
             'Garnet Circle Cir',
             'Ginger Cir',
             'Glades Cir',
             'Greens Edge Cir',
             'Harbor Pointe Cir',
             'Harbor View Cir',
             'Island Cir',
             'Jasmine Cir',
             'Kinsington Cir',
             'La Costa Cir',
             'Lakeshore Cir',
             'Lakewood Cir',
             'Laurel Ridge Cir',
             'Lavender Cir',
             'Mira Vista Cir',
             'Montclaire Cir',
             'Oak Ridge Cir',
             'Passion Vine Cir',
             'Pond Ridge Cir',
             'Poplar Cir',
             'Portofino Cir',
             'Provence Cir',
             'Riviera Cir',
             'Sabal Ridge Cir',
             'Sago Cir',
             'Sailboat Cir',
             'Salerno Cir',
             'San Simeon Cir',
             'Sand Creek Cir',
             'Sand Creel Cir',
             'Sandpiper Cir',
             'Seagrape Cir',
             'Sevilla Cir',
             'Seville Cir',
             'Simonton Cir',
             'Spoonbill Cir',
             'St Tropez Cir',
             'Sunflower Cir',
             'Tanglewood Cir',
             'Town Center Cir',
             'Tulip Cir',
             'Victoria Pointe Cir',
             'Vineyard Cir',
             'Waterside Cir',
             'Whitehead Cir',
             'Windward Cir']),
 'Circle': set(['East Rogers Circle',
                'Misty Oaks Circle',
                'South Rogers Circle',
                'West Rogers Circle']),
 'Cirlce': set(['Alhambra Cirlce']),
 'Columbia': set(['Columbia']),
 'Cres': set(['Country Club Cres']),
 'Crescent': set(['Swansea Crescent']),
 'Ct': set(['Ansley Ct',
            'Balboa Ct',
            'Bay Ct',
            'Bay Isle Ct',
            'Bay Pointe Ct',
            'Boston Ct',
            'Bowman Ct',
            'Cameron Ct',
            'Cedar Ct',
            'Cherrywood Ct',
            'Clermont Ct',
            'Condor Ct',
            'Crossbill Ct',
            'Croton Ct',
            'Crystal Ct',
            'Cygnus Ct',
            'Danielle Ct',
            'Deerpath Ct',
            'Duval Ct',
            'Eagle Ct',
            'Eagle Run Ct',
            'Eagle Watch Ct',
            'Edgewater Ct',
            'Edgewater Ct Ct',
            'Egret Ct',
            'Fairfax Ct',
            'Fleming Ct',
            'Fox Creek Ct',
            'Fox Run Ct',
            'Glenwood Ct',
            'Greenbrier Ct',
            'Gulfstream Ct',
            'Hampton Ct',
            'Harbor Ct',
            'Hawks Ct',
            'Holly Ct',
            'Hunter Ct',
            'Iris Ct',
            'Ironwood Ct',
            'Jade Ct',
            'Jardin Ct',
            'Key West Ct',
            'Kite Ct',
            'La Costa Ct',
            'Lake Crest Ct',
            'Lakeview Ct',
            'Lakewood Ct',
            'Lantana Ct',
            'Laurel Ct',
            'Lido Ct',
            'Lighthouse Ct',
            'Mallory Ct',
            'Manor Ct',
            'Maplewood Ct',
            'Marseille Ct',
            'Martin Ct',
            'Martinique Ct',
            'Meadowood Ct',
            'Miller Ct',
            'Montclaire Ct',
            'Monterey Ct',
            'Nelson Ct',
            'Oakbrook Ct',
            'Oakmont Ct',
            'Osprey Ct',
            'Park Ct',
            'Patio Village Ct',
            'Penta Ct',
            'Pine Branch Ct',
            'Pine Ridge Ct',
            'Pinecrest Ct',
            'Placid Ct',
            'Poinciana Ct',
            'Pompeii Ct',
            'Princeton Ct',
            'Provence Ct',
            'Quail Ct',
            'Riviera Ct',
            'Royal Poinciana Ct',
            'SW 15th Ct',
            'SW 4th Ct',
            'SW 5th Ct',
            'Sapphire Ct',
            'Smoke Tree Ct',
            'Sorrel Ct',
            'Stillwater Ct',
            'Tamarind Ct',
            'Terrystone Ct',
            'Thistle Creek Ct',
            'Thrush Ct',
            'Turnstone Ct',
            'Verona Ct',
            'Water Ridge Ct',
            'Waterview Ct',
            'West 28th Ct',
            'Woodfall Ct']),
 'Cv': set(['Sapphire Cv']),
 'Dr': set(['Amber Bay Dr',
            'Bay Isle Dr',
            'Bay Point Dr',
            'Bay Pointe Dr',
            'Bermuda Springs Dr',
            'Cambridge Dr',
            'Camellia Dr',
            'Cameron Dr',
            'Canary Island Dr',
            'Carrington Dr',
            'Cascade Falls Dr',
            'Cedar Falls Dr',
            'Center Court Dr',
            'Chinaberry Dr',
            'Conservation Dr',
            'Creekford Dr',
            'Diamond Dr',
            'Diamond Head Dr',
            'E Bay Dr',
            'E Bayridge Dr',
            'Eagle Run Dr',
            'Edgewater Dr',
            'Elderberry Dr',
            'Emerald Estates Dr',
            'Executive Park Dr',
            'Fairfield Meadows Dr',
            'Falcon Ridge Dr',
            'Fern Dr',
            'Forest Dr',
            'Fox Ridge Dr',
            'Golden Cane Dr',
            'Golf View Dr',
            'Golfview Dr',
            'Harbor View Dr',
            'Harbour Side Dr',
            'Hemingway Dr',
            'Heritage Dr',
            'Highland Meadows Dr',
            'Jardin Dr',
            'La Costa Dr',
            'Laguna Springs Dr',
            'Lake Point Dr',
            'Lake Tree Dr',
            'Lakeshore Dr',
            'Lakeview Dr',
            'Lakewood Dr',
            'Lantana Dr',
            'Laurel Dr',
            'Madeira Dr',
            'Magnolia Ridge Dr',
            'Magnoliaridge Dr',
            'Mahagany Ridge Dr',
            'Mahogany Ridge Dr',
            'Mahoganyridge Dr',
            'Malibu Dr',
            'Mallard Dr',
            'Manatee Isles Dr',
            'Mango Dr',
            'Maple Dr',
            'Marina Dr',
            'Meadowood Dr',
            'Montclaire Dr',
            'N Kendall Dr',
            'N University Dr',
            'Nandina Dr',
            'Nautica Dr',
            'Nighthawk Dr',
            'Northpark Dr',
            'Oakbrook Dr',
            'Opal Creek Dr',
            'Palermo Dr',
            'Peppertree Dr',
            'Pine Branch Dr',
            'Pine Lake Dr',
            'Pinecrest Dr',
            'Pinehurst Dr',
            'Poinciana Dr',
            'Pond Apple Dr',
            'Presidio Dr',
            'Primrose Dr',
            'Prsidio Dr',
            'Quail Roost Dr',
            'Racquet Club Dr',
            'River Oaks Dr',
            'Riviera Cir Dr',
            'Royal Fern Dr',
            'Royal Poinciana Dr',
            'S Manor Dr',
            'S Ocean Dr',
            'SW Royal Poinciana Dr',
            'San Marco Dr',
            'San Remo Dr',
            'Sanctuary Dr',
            'Sapphire Dr',
            'Savanna Commons Dr',
            'Savannah Falls Dr',
            'Skylark Dr',
            'Sorrento Dr',
            'Spinnaker Dr',
            'Sportsplex Dr',
            'Springside Dr',
            'Stanton Dr',
            'Stonemont Dr',
            'Tree Top Dr',
            'Truman Dr',
            'Verona Lake Dr',
            'Victoria Isle Dr',
            'Village Lake Dr',
            'Vista Meadows Dr',
            'W Bayridge Dr',
            'Water Ridge Dr',
            'Waters Edge Dr',
            'Waterview Dr',
            'West City Dr',
            'Weston Hills Dr',
            'Willow Dr',
            'Willow Ridge Dr']),
 'HWY': set(['29901 S DIXIE HWY']),
 'Highway': set(['Dixie Highway',
                 'Federal Highway',
                 'North Dixie Highway',
                 'North Federal Highway',
                 'Old Dixie Highway',
                 'S Dixie Highway',
                 'South Dixie Highway',
                 'South Federal Highway',
                 'West Dixie Highway']),
 'Holw': set(['Fox Holw']),
 'Huntington': set(['Huntington']),
 'Hwy': set(['Beeline Hwy',
             'Main Hwy',
             'N Dixie Hwy',
             'N. Federal Hwy',
             'S Dixie Hwy',
             'US 27 Hwy']),
 'Hwy-1': set(['US Hwy-1']),
 'Inverness': set(['Inverness']),
 'Isle': set(['Sapphire Isle']),
 'Lake': set(['Amber Lake', 'Ruby Lake']),
 'Ln': set(['Amber Ln',
            'Andromeda Ln',
            'Aspen Ln',
            'Azure Ln',
            'Bahia Ln',
            'Bamboo Ln',
            'Bayridge Ln',
            'Bayside Ln',
            'Bell Tower Ln',
            'Blossom Ln',
            'Boot Ln',
            'Briar Ln',
            'Bridle Path Ln',
            'Bunting Ln',
            'Cambridge Ln',
            'Camellia Ln',
            'Cammi Ln',
            'Capri Ln',
            'Carrington Ln',
            'Cherry Ln',
            'Chestnut Ln',
            'Cove Ln',
            'Crestview Ln',
            'Crossbill Ln',
            'Cypress Ln',
            'Daisy Ln',
            'Deerwood Ln',
            'Derby Ln',
            'Diamond Pointe Ln',
            'Eagle Run Ln',
            'Eagle Watch Ln',
            'Eastwood Ln',
            'Egret Ln',
            'Fairfax Ln',
            'Fairfield Ln',
            'Fairmont Ln',
            'Fairway Ln',
            'Fox Glove Ln',
            'Foxtail Ln',
            'Greenbriar Ln',
            'Heron Ridge Ln',
            'Hidden Trail Ln',
            'Honeysuckle Ln',
            'Ibis Ln',
            'Ivy Ln',
            'Jardin Ln',
            'Juniper Ln',
            'Kelly Ln',
            'La Costa Ln',
            'Lake Ridge Ln',
            'Live Oak Ln',
            'Lone Pine Ln',
            'Mahogany Ln',
            'Mallard Ln',
            'Mariners Ln',
            'Mayfair Ln',
            'Meadow Ln',
            'Newport Ln',
            'Oak Ridge Ln',
            'Oakbrook Ln',
            'Oakwood Ln',
            'Old Still Ln',
            'Orange Tree Ln',
            'Orion Ln',
            'Paddock Ln',
            'Pasa Verde Ln',
            'Patio Village Ln',
            'Pheasant Ln',
            'Pine Ridge Ln',
            'Pinewood Ln',
            'Poinciana Ln',
            'Reflection Ln',
            'Saddle Ln',
            'Saddlebrook Ln',
            'Sago Ln',
            'San Simeon Ln',
            'Sandalwood Ln',
            'Sanderling Ln',
            'Sapphire Ln',
            'Schooner Ln',
            'Sequoia Ln',
            'Shadyside Ln',
            'Silktree Ln',
            'Sirius Ln',
            'Sparrow Ln',
            'Spyglass Ln',
            'St Gabrielle Ln',
            'Staghorn Ln',
            'Stallion Ln',
            'Stanton Ln',
            'Stirrup Ln',
            'Stonemont Ln',
            'Surrey Ln',
            'Timber Cove Ln',
            'Trailmore Ln',
            'Twin Branch Ln',
            'Veracruz Ln',
            'Victoria Isle Ln',
            'Victoria Point Ln',
            'Victoria Pointe Ln',
            'Vista Grove Ln',
            'Waterbrook Ln',
            'Waterview Ln',
            'Westwood Ln',
            'Willow Ln',
            'Windsor Ln',
            'Winterberry Ln']),
 'Longview': set(['Longview']),
 'Manor': set(['Cypress Manor', 'Northwest 11th Manor']),
 'Medinah': set(['Medinah']),
 'Merion': set(['E Merion']),
 'Mnr': set(['Cypress Mnr',
             'Jardin Mnr',
             'Oakbrook Mnr',
             'Pine Ridge Mnr',
             'Riviera Mnr',
             'Sapphire Mnr']),
 'Muirfield': set(['Muirfield']),
 'N/A': set(['N/A N/A N/A']),
 'NW': set(['Broken Sound Pky NW']),
 'North': set(['140th Avenue North', 'Falls Circle Drive North']),
 'Oakmont': set(['Oakmont']),
 'Path': set(['SW 138th Path']),
 'Pkwy': set(['6900 Miramar Pkwy',
              'Glades Pkwy',
              'Meridian Pkwy',
              'N Commerce Pkwy',
              'S Commerce Pkwy']),
 'Pl': set(['Azalea Pl',
            'Blatt Pl',
            'Diamond Pl',
            'Jardin Pl',
            'Laurel Pl',
            'Palm Pl',
            'Palmer Pl',
            'Sapphire Pl',
            'Verona Pl']),
 'Plaza': set(['Commodore Plaza']),
 'Poinciana': set(['Via Poinciana']),
 'Pt': set(['Water Pt']),
 'RD': set(['E McNab RD']),
 'Raleigh': set(['Raleigh']),
 'Rd': set(['Airport Rd',
            'Bald Cypress Rd',
            'Birchwood Rd',
            'Bird Rd',
            'Briar Ridge Rd',
            'Bridgeton Rd',
            'Chimney Rock Rd',
            'Clint Moore Rd',
            'Cordova Rd',
            'Coronad Rd',
            'Coronado Rd',
            'Country Club Rd',
            'Country Isles Rd',
            'Deer Creek Rd',
            'Elm Grove Rd',
            'Emerald Cove Rd',
            'Fairmont Rd',
            'Falling Water Rd',
            'Garden Rd',
            'Glades Rd',
            'Golf Club Rd',
            'Green Toad Rd',
            'Greenwood Rd',
            'Hackney Rd',
            'Heron Rd',
            'Hunter Rd',
            'Lincoln Rd',
            'Luckie Rd',
            'Lyons Rd',
            'Mallard Rd',
            'NW Le Jeune Rd',
            'Nighthawk Rd',
            'Paddock Rd',
            'Racquet Club Rd',
            'Ranch Rd',
            'Regal Cove Rd',
            'River Oaks Rd',
            'S Post Rd',
            'S Red Rd',
            'Saddle Club Rd',
            'Seabay Rd',
            'Seminole Pratt Whitney Rd',
            'Slippery Rock Rd',
            'South Post Rd',
            'Talavera Rd',
            'Talvera Rd',
            'Three Village Rd',
            'Timberline Rd',
            'Weston Rd',
            'Willow Bend Rd',
            'Windmill Lake Rd',
            'Windmill Ranch Rd']),
 'Rd.': set(['3196 N. Jog Rd.', 'Alton Rd.', 'Bird Rd.']),
 'Rey': set(['San Luis Rey']),
 'Rouge': set(['Baton Rouge']),
 'Row': set(['Diamond Row']),
 'Run': set(['Silks Run', 'Turtle Run']),
 'ST': set(['12970 SW 268TH ST', 'SW 15th ST']),
 'Sacramento': set(['Sacramento']),
 'Somerset': set(['Somerset']),
 'South': set(['Falls Circle Drive South', 'Grand Bay Drive South']),
 'Spgs': set(['Sapphire Springs Spgs', 'Sunset Springs Spgs']),
 'Spinnaker': set(['Spinnaker']),
 'Spyglass': set(['Spyglass']),
 'Sr': set(['84 Sr', 'W 84 Sr']),
 'St': set(['3339 W 80th St',
            'Austin St',
            'Crystal St',
            'Denver St',
            'Dover St',
            'E Hibiscus St',
            'Main St',
            'Market St',
            'Montpeliar St',
            'N Hibiscus St',
            'NE 1st St',
            'NE 46th St',
            'NE 62nd St',
            'NW 12th St',
            'NW 27th St',
            'NW 33rd St',
            'NW 51st St',
            'NW 58th St',
            'Northeast 44th St',
            'Park Ridge St',
            'S Hibiscus St',
            'SW 15th St',
            'SW 26th St',
            'SW 5th St',
            'SW 88th St',
            'Sacramento St',
            'Sapphire St',
            'Southwest 211th St',
            'Stonebrook St',
            'Tallahassee St',
            'W Flagler St',
            'W Hibiscus St',
            'Waters Edge St']),
 'St.': set(['NW 58th St.']),
 'Ste': set(['Sunny Isles Blvd Ste']),
 'Ter': set(['Bluewood Ter',
             'Cambridge Ter',
             'Cascade Ter',
             'Diamond Ter',
             'Dockside Ter',
             'Ensenada Ter',
             'Fairway Ter',
             'Fishtail Ter',
             'Hacienda Ter',
             'Hawthorn Ter',
             'Jardin Ter',
             'Majesty Ter',
             'Opal Ter',
             'Patio Village Ter',
             'Pisces Ter',
             'SW 166th Ter',
             'SW 167th Ter',
             'SW 168th Ter',
             'SW 169th Ter',
             'Sapphire Ter',
             'Silverbell Ter',
             'Springside Ter',
             'Sweetgum Ter',
             'Sycamore Ter',
             'Vanda Ter']),
 'Terrace': set(['Constant Springs Terrace',
                 'Norhwest 49th Terrace',
                 'Northeast 208th Terrace',
                 'Northeast 59th Terrace',
                 'Northwest 107th Terrace',
                 'Northwest 13th Terrace',
                 'Ocean Terrace',
                 'Pine Tree Terrace',
                 'SW 16th Terrace',
                 'Southeast 12th Terrace',
                 'Southeast 14th Terrace',
                 'Southwest 101 Terrace',
                 'Southwest 21st Terrace',
                 'Southwest 271st Terrace',
                 'Southwest 28th Terrace']),
 'Trace': set(['wellington Trace']),
 'Trce': set(['Indian Trce', 'Tequesta Trce']),
 'Trl': set(['N Military Trl',
             'Palmetto Trl',
             'S. Military Trl',
             'Sabal Trl',
             'Turquoise Trl']),
 'Way': set(['Alhambra Way',
             'Allamanda Way',
             'Amber Way',
             'Areca Way',
             'Aster Way',
             'Banyan Way',
             'Barcelona Way',
             'Bedford Way',
             'Birchwood Way',
             'Biscayne Boulevard Way',
             'Borealis Way',
             'Breakers Way',
             'Bridgeton Way',
             'Cardinal Way',
             'Caribbean Way',
             'Cinnamon Way',
             'Country Club Way',
             'Crescent Way',
             'Cypress Island Way',
             'Diamond Way',
             'Dogwood Way',
             'E Coquina Way',
             'Eagle Run Way',
             'Eastlake Way',
             'Egret Way',
             'Espanola Way',
             'Fairmont Way',
             'Gander Way',
             'Gulf Stream Way',
             'Harbor Way',
             'Harbour Pointe Way',
             'Heritage Way',
             'Hickory Way',
             'Hidden Valley Way',
             'Hippocrates Way',
             'Hunters Run Way',
             'Island Way',
             'Jardin Way',
             'Kapok Way',
             'La Costa Way',
             'Landing Way',
             'Leeward Way',
             'Max Planck Way',
             'Merrick Way',
             'N Coquina Way',
             'Pasadena Way',
             'Patio Village Way',
             'Peregrine Way',
             'Phoenix Way',
             'Pigeon Plum Way',
             'Plumosa Way',
             'Redwood Way',
             'Royal Grove Way',
             'Royal Palm Way',
             'S Coquina Way',
             'S Landing Way',
             'SW 168th Way',
             'SW 169th Way',
             'SW 5th Way',
             'Sabal Way',
             'Sansburys Way',
             'Scripps Way',
             'Seminole Way',
             'Silver Palm Way',
             'Somerset Way',
             'Stone Ridge Way',
             'Sunset Springs Way',
             'Sunset Way',
             'Truck and Trailer Way',
             'Tupelo Way',
             'Ultimate Way',
             'Victoria Isle Way',
             'Vista Way',
             'W Coquina Way',
             'Walkers Way',
             'Windward Way',
             'Zenith Way']),
 'Wentworth': set(['Wentworth']),
 'West': set(['Marina Bay Drive West']),
 'Westbrook': set(['Westbrook']),
 'Wiles': set(['Wiles']),
 'ave': set(['southwest 112th ave']),
 'st': set(['NW 27th st']),
 'street': set(['184th street', 'sw 8th street'])}
 '''